### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by zychappy** [rakanalh/scheduler#14]
scheduler/storage/mongo.go:77:12: undefined: bson.NewDocument
scheduler/storage/mongo.go:77:29: undefined: bson.EC
scheduler/storage/mongo.go:111:12: undefined: bson.NewDocument
scheduler/storage/mongo.go:111:29: undefined: bson.EC
scheduler/storage/mongo.go:138:11: undefined: bson.NewDocument

**Comment by rakanalh** [comment]
Hi @zychappy 

You can try the following:
```
go get ./...
```
Should fix your issue

**Comment by fbettag** [comment]
Your fix doesn't work :(

`[fbettag@w0rk ~/go/src/my/go-mod-bla] $ go get github.com/rakanalh/scheduler
go: finding github.com/rakanalh/scheduler latest
go: downloading github.com/rakanalh/scheduler v0.0.0-20181003095030-d081b7053e0d
go: finding github.com/mongodb/mongo-go-driver/mongo latest
go: finding github.com/mongodb/mongo-go-driver/bson latest
go: finding github.com/mongodb/mongo-go-driver v0.1.0
go: downloading github.com/mongodb/mongo-go-driver v0.1.0
go: finding github.com/golang/snappy latest
go: finding github.com/xdg/stringprep v1.0.0
go: finding github.com/xdg/scram latest
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/xdg/stringprep v1.0.0
# github.com/rakanalh/scheduler/storage
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:77:12: undefined: bson.NewDocument
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:77:29: undefined: bson.EC
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:111:12: undefined: bson.NewDocument
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:111:29: undefined: bson.EC
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:138:11: undefined: bson.NewDocument
zsh: exit 2     go get github.com/rakanalh/scheduler

[fbettag@w0rk ~/go/src/my/go-mod-bla] $ go get github.com/rakanalh/scheduler/...
go: finding github.com/rakanalh/scheduler latest
# github.com/rakanalh/scheduler/storage
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:77:12: undefined: bson.NewDocument
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:77:29: undefined: bson.EC
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:111:12: undefined: bson.NewDocument
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:111:29: undefined: bson.EC
../../../../pkg/mod/github.com/rakanalh/scheduler@v0.0.0-20181003095030-d081b7053e0d/storage/mongo.go:138:11: undefined: bson.NewDocument
zsh: exit 2     go get github.com/rakanalh/scheduler/...
`

**Comment by license2e** [comment]
Still broken...
