### ISSUE TITLE
support for postgres db and clean up connections at scheduler stop

### ISSUE THREAD

**Issue by jnanasagar** [rakanalh/scheduler#8]
Hi,

We had a need to use this scheduler with postgres db.

I have made the changes to support the postgres db accordingly and also to clean up the connections at scheduler stop.

Whereas I'm unable to push the changes to a branch and raise PR, with error 
```
remote: Permission to rakanalh/scheduler.git denied to jnanasagar.
fatal: unable to access 'https://github.com/rakanalh/scheduler/': The requested URL returned error: 403
```

Can you please give me access, so that I can push the changes to a branch and raise PR accordingly.

Thanks,
Jnana.

**Comment by rakanalh** [comment]
Hello @jnanasagar,

That's not how it works. What you should do, is "Fork" the repo (button on right-most side at the top of this page) and create your own clone. Then you clone your version of the repo and make changes by committing to it. Then you push to your "origin" which is going to be github.com/jnanasagar/scheduler and then you create a Pull request that i can review and see if it's suitable for inclusion in this repo.

Please take the time to familiarize yourself with how Forking and Pull requests here: https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by jnanasagar** [comment]
Hey @rakanalh,

Thanks. I have raised a PR accordingly, please take time to review it.

**Comment by rakanalh** [comment]
This has been implemented and merged into master.
